- hosts: linux
  tasks:
    - name: Add repo key
      apt_key:
        key_server: keyserver.ubuntu.com
        id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
        state: present
    - name: Add osquery repo
      apt_repository:
        repo: deb [arch=amd64] https://pkg.osquery.io/deb deb main
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes
        state: present
    - name: Install osquery
      apt:
        name: osquery
        state: present
    - debug:
        var: result.stdout_lines

- hosts: windows
  tasks:
    - name: Install chocolatey
      win_command: powershell.exe -
      args:
        stdin: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) && SET "PATH=%PATH%;%ALLUSERSPROFILE%\\chocolatey\\bin"

    - name: Install osquery
      win_chocolatey:
        name: osquery
        state: present
    - name: Enable Win Event Log
      win_command: powershell.exe -
        args:
          stdin: Set-ExecutionPolicy Bypass -Scope Process -Force; C:\\ProgramData\\osquery\\manage-osqueryd.ps1 -inbstallWelManifest
    - debug:
        var: result.stdout_lines
