- hosts: linux
  become: true
  tasks:
    - name: Add repo key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
        state: present
    
    - name: Add osquery repo
      apt_repository:
        repo: deb [arch=amd64] https://pkg.osquery.io/deb deb main
        state: present
    
    - name: Update apt cache
      apt:
        update_cache: yes
        state: present

    - name: Install osquery
      apt:
        name: osquery
        state: present

- hosts: windows
  become_method: runas
  become_user: alice
  tasks:
    - name: Install chocolatey
      win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      become: true

    - name: Install osquery
      win_chocolatey:
        name: osquery
        state: present

    - name: Add osqueryi to PATH
      win_path:
        elements:
          - C:\Program Files\osquery
        state: present

    #- name: Enable Win Event Log
    #  win_command: powershell.exe -Set-ExecutionPolicy Bypass -Scope Process -Force; "C:\\ProgramData\\osquery\\manage-osqueryd.ps1" -installWelManifest
    #  become: true
