- hosts: linux
  tasks:
    - name: Get recent logins
      shell: osqueryi --list "select * from logged_in_users"
      register: logins

    - name: Get processes
      shell: osqueryi --list "select pid,name,uid from processes"
      register: processes

    - name: Get outbound connections
      shell: osqueryi --list "select * from process_open_sockets where remote_port != 80 and remote_port != 443 and state != 'listen'"
      register: connections

    - debug:
        msg:
          - "Recent logins"
          - "{{ logins.stdout_lines }}"
          - "Running processes"
          - "{{ processes.stdout_lines }}"
          - "Outbound connections"
          - "{{ connections.stdout_lines }}"

- hosts: windows
  tasks:
    - name: Get recent logins
      win_command: osqueryi.exe --list "select logon_id,user,logon_domain,logon_sid from logon_sessions"
      register: logins

    - name: Get processes
      win_command: osqueryi.exe --list "select pid,name,uid from processes"
      register: processes

    - name: Get outbound connections
      win_command: osqueryi.exe --list "select * from process_open_sockets where remote_port != 80 and remote_port != 443 and state != 'listen'"
      register: connections
      when: inventory_hostname != "winserv"

    - debug:
        msg:
          - "Recent logins"
          - "{{ logins.stdout_lines }}"
          - "Running processes"
          - "{{ processes.stdout_lines }}"

    - debug:
        msg:
          - "Outbound connections"
          - "{{ connections.stdout_lines }}"
      when: inventory_hostname != "winserv"