- hosts: linux
  tasks:
    - name: Get installed applications
      shell: osqueryi --list "select name from deb_packages"
      register: applications

    - name: Get startup programs
      shell: osqueryi --list "select name,path from processes where parent=1"
      register: startup

    - name: Print host information
      debug:
        msg:
          - "Installed applications"
          - "{{ applications.stdout_lines | reject('equalto', '') | list }}"
          - "Startup programs"
          - "{{ startup.stdout_lines }}"

- hosts: windows
  become: true
  become_method: runas
  become_user: alice
  tasks:
    - name: Get installed applications
      win_command: osqueryi.exe --list "select name from programs"
      register: applications

    - name: Get startup programs
      win_command: osqueryi.exe --list "select name,path from startup_items"
      register: startup

    - name: Print host information
      debug:
        msg:
          - "Installed applications"
          - "{{ applications.stdout_lines | reject('equalto', '') | list }}"
          - "Startup programs"
          - "{{ startup.stdout_lines }}"
