- hosts: linux
  tasks:
    - name: Get hostname
      shell: echo "select local_hostname from system_info;" | osqueryi
      register: hostname

    - name: Get IP information
      shell: echo "select friendly_name,address from interface_addresses;" | osqueryi
      register: ips

    - name: Get users
      shell: echo "select username,description from users;" | osqueryi
      register: users
      
    - name: Get OS information
      shell: echo "select name,patch,build from os_version;" | osqueryi
      register: os

    - debug:
        msg:
          - "Hostname"
          - "{{ hostname.stdout }}"
          - "IP Addresses"
          - "{{ ips.stdout }}"
          - "Users"
          - "{{ users.stdout }}"
          - "OS Information"
          - "{{ os.stdout }}"

- hosts: windows
  tasks:
    - name: Get hostname
      win_command: echo "select local_hostname from system_info;" | osqueryi
      args:
        executable: cmd
      register: hostname

    - name: Get connected domain
      win_command: echo "select name from ntdomains;" | osqueryi
      args:
        executable: cmd
      register: domain

    - name: Get IP information
      win_command: echo "select friendly_name,address from interface_addresses;" | osqueryi
      args:
        executable: cmd
      register: ips

    - name: Get users
      win_command: echo "select username,description from users;" | osqueryi
      args:
        executable: cmd
      register: users
      
    - name: Get OS Information
      win_command: echo "select name,patch,build from os_version;" | osqueryi
      args:
        executable: cmd
      register: win_os

    - debug:
        msg:
          - "Hostname"
          - "{{ hostname.stdout }}"
          - "Domain"
          - "{{ domain.stdout }}"
          - "IP Addresses"
          - "{{ ips.stdout }}"
          - "Users"
          - "{{ users.stdout }}"
          - "OS Information"
          - "{{ win_os.stdout }}"
